### ISSUE TITLE
FPS drops to 1

### ISSUE THREAD

**Issue by a840409g** [KenYu910645/MapleStoryAutoLevelUp#66]
我已按照 README 安裝依賴 並執行腳本 但人物只會做走跳與爬梯行為
我僅修改了 edit_me 如下
```
key:
  aoe_skill: "space"            # 💥 Set to the AoE skill key. Choose a key with low cooldown.
  directional_attack: ""   # ⚔️ Assign to your main spammable attack.
  teleport: ""             # 🌀 Leave empty ("") if your class can’t teleport.
  jump: "z"             # 🦘 Set to jump. No need to change unless you use a non-standard key.
  add_hp: ""               # ❤️ Assign to HP potion hotkey. Match with your potion shortcut.
  add_mp: ""               # 💧 Assign to MP potion hotkey. Match with your potion shortcut.

# 🧙 BUFF SKILLS
# Add keys for buffs you want to auto-cast. Match cooldowns with actual in-game durations.
# buff_skill:
#   keys: ["a", "s"]          # ⌨️ Add one or more buff keys here (in order).
#   cooldown: [180, 90]       # ⏱️ Set each skill’s cooldown (seconds). Be precise to avoid spamming.

# ⚔️ DIRECTIONAL ATTACK SETTINGS
# Tune these by observing the debug window.
# Smaller range -> you will fight monster in close-range combat
# Larger range -> you will attack monster far away, but could hit nothing if it's set to large
# directional_attack:
  # range_x: 320              # ↔️ Try reducing if you’re hitting unreachable monsters.
  # range_y: 60               # ↕️

# 💥 AOE SKILL SETTINGS
# Similar to directional attack. Adjust to match your AoE hitbox on screen.
aoe_skill:
  range_x: 50              # ↔️ Try reducing if you’re hitting unreachable monsters.
  range_y: 50              # ↕️

# ❤️ HEALTH MONITOR
# Use this to auto-drink potions at specific HP/MP thresholds.
health_monitor:
  enable: False              # ✅ Set to False if using pet auto-heal.
#   add_hp_ratio: 0.4         # ❤️ drink potion when HP is below this number
#   add_mp_ratio: 0.5         # 💙 drink potion when MP is below this number
```
請問我哪邊設置錯誤?我懷疑是 name tag 有錯 所以也附上我修改的 name tag
![Image](https://github.com/user-attachments/assets/e751baeb-1587-4362-a8ca-4baa44af94e7)

**Comment by gjp4tw** [comment]
前幾天執行也沒問題 剛剛sync to head也不會打怪了 只會來回走動

**Comment by Smallaaa0404** [comment]
你可以試試看直接更改config_default.yaml的參數，看看能不能正常運行
如果你懷疑name tag有問題的話，你可以在運行腳本的時候你可以看看debug window 中的name tag有沒有被正確識別，有的話代表你的name tag沒問題

**Comment by a840409g** [comment]
> 你可以試試看直接更改config_default.yaml的參數，看看能不能正常運行 如果你懷疑name tag有問題的話，你可以在運行腳本的時候你可以看看debug window 中的name tag有沒有被正確識別，有的話代表你的name tag沒問題

我試著修改 default.yml 基本上只改攻擊鍵以及取消藥水使用 如下
```yaml
key:
  aoe_skill: "space"            # 💥 AoE skill (e.g., Cleric's heal or Mage's lightning)
  directional_attack: "9"   # ⚔️ Basic directional attack (e.g., Magic Claw or throwing stars)
  teleport: ""             # 🌀 Teleport skill. Set to "" if not usable
  jump: "z"             # 🦘 Jump key
  add_hp: ""               # ❤️ Use HP potion. Set to "" to disable auto-healing
  add_mp: ""               # 💧 Use MP potion. Set to "" to disable auto-mana

aoe_skill:
  range_x: 400               # ↔️ Horizontal skill range (in pixels)
  range_y: 170               # ↕️ Vertical skill range (in pixels)

# 中間為初始設定
health_monitor:
  enable: False             # ✅ Enable or disable health monitor
  force_heal: False      # 🛡️ Heal first — stop attacking until HP is restored
  add_hp_ratio: 0.5        # ❤️ Drink HP potion when HP drops below this ratio [0.0 ~ 1.0]
  add_mp_ratio: 0.5        # 💙 Drink MP potion when MP drops below this ratio [0.0 ~ 1.0]
  add_hp_cooldown: 0.5     # 🕒 Seconds to wait between HP potions, prevent potion spam
  add_mp_cooldown: 0.5     # 🕒 Seconds to wait between MP potions, prevent potion spam
  fps_limit: 20            # 🚥 Loop rate for the health monitor thread
# 以下為初始設定
```
執行跑的地圖為預設
```
python mapleStoryAutoLevelUp.py --map lost_time_1 --monsters evolved_ghost
```
結果如[錄影](https://drive.google.com/file/d/1kAAzjp2QpN06RWQQkfiBxCdyBv2aOpsU/view?usp=sharing)
